_MAP_ARTIST_TO_GENRE = {
    'snoopdogg': 'rap',
    'pussyriot': None,
    'salemilese': 'pop',
    'danielallan': 'other',
    'rac': 'pop',
    'soulection': None,
    'boredbrothers': None,
    'oshi': 'vapor twitch',
    'imaneurope': 'r&b',
    'callmelatasha': 'rap',
    'grady': 'pop',
    'chaim': 'r&b',
    'alann8h': None,
    'marianhill': 'pop',
    'aluna': 'electronic',
    'jonwaltz': 'hip hop',
    'maelstrom': None,
    'allankingdom': 'other',
    'alexander23': 'pop',
    'reocragun': 'hip hop',
    'samgellaitry': 'electronic',
    'sophiaalexa': 'other',
    'notd': 'pop',
    'abjo': 'vapor twitch',
    'camoufly': 'vapor twitch',
    'heno': 'other',
    'medasin': 'electronic',
    'bloodywhite': 'pop',
    'brux': 'other',
    'sango': 'r&b',
    'tokimonsta': None,
    'joshpan': 'rap',
    'paulineherr': 'other',
    'boysnoize': 'electronic',
    'poolside': None,
    'pollen': None,
    'vicmensa': 'rap',
    'thepark': 'other',
    'cleareyes': 'other',
    'patlok': None,
    'shmurda': 'rap',
    'harryhudson': 'pop',
    'ibninglor': 'other',
    'tomi': 'other',
    'jutes': 'rap',
    'lyrah': 'other',
    'kilokish': 'r&b',
    'moruf': None,
    'tk': 'other',
    'jesseboykins3rd': 'r&b',
    'siimbiie': None,
    'tika': 'r&b',
    'benkessler': 'other',
    'blondish': 'electronic',
    'sassyblack': 'other',
    'mcclenney': 'r&b',
    'karmawav': 'other',
    'melvv': 'pop',
    'kaiencruz': None,
    'dot': 'other',
    'alainacastillo': 'r&b',
    'pjsaputo': 'other',
    'twerl': 'rap',
    'slenderbodies': None,
    'jacquesgreene': None,
    'thedramaduo': None,
    'oksami': 'other',
    'giraffage': 'pop',
    'partypupils': 'pop',
    'alecking': 'pop',
    'lakim': 'vapor twitch',
    'alexanderlewis': 'rap',
    'superflirt': 'other',
    'tesshenley': 'pop',
    'blackdave': 'other',
    'itsmarkjohns': 'other',
    'dazmerchant': 'other',
    'whethan': None,
    'sloejack': None,
    'iamdnmo': 'other',
    'twofeet': 'pop',
    'tensnake': 'electronic',
    'rubyred': 'other',
    'findokmusic': 'other',
    'dlg': None,
    'msft': 'other',
    'sukiwaterhouse': 'pop',
    'hayleygenepenner': 'other',
    'alara': None,
    'deffie': 'vapor twitch',
    '3v3ry1': None,
    'beautyschooldropout': None,
    'harriscole': None,
    'glowstone': 'other',
    'krs': None,
    'felly': None,
    'munn': 'other',
    'iamnobodi': 'r&b',
    'jrobb': 'other',
    'bearson': 'pop',
    'jameecornelia': 'other',
    'lnrz': None,
    'streetfever': None,
    'sherwyn': 'other',
    'reinenr3alm': 'other',
    'nova': None,
    'devault': None,
    'beingthere': None,
    'carlathepoet': 'other',
    'duskus': None,
    'jezdior': 'pop',
    'rizlavie': None,
    'yahzarah': 'other',
    'katenash': 'pop',
    'grentperez': 'r&b',
    'vaultboy': 'pop',
    'queengeorge': 'other',
    'sadalex': None,
    'thomasjack': None,
    'brandonbanks': None,
    'camden_music': 'other',
    'cameronavery': 'other',
    'brevinkim': 'hip hop',
    'jerryfolk': 'vapor twitch',
    'lucamaxim': None,
    'rozetzetzet': None,
    'dwilly': None,
    'devintracy': 'r&b',
    'gigamesh': 'other',
    'tulengua': None
}

_MAP_NAME_TO_SOUND = {
    'Snoop Dogg': 'snoopdogg',
    'Pussy Riot': 'pussyriot',
    'salem ilese': 'salemilese',
    'Daniel Allan': 'danielallan',
    'RAC': 'rac',
    'Soulection': 'soulection',
    'Bored Brothers': 'boredbrothers',
    'oshi': 'oshi',
    'Iman Europe': 'imaneurope',
    'LATASHÁ': 'callmelatasha',
    'Grady': 'grady',
    'Matthew Chaim': 'chaim',
    'Marian Hill': 'marianhill',
    'Aluna': 'aluna',
    'JON WALTZ': 'jonwaltz',
    'Maelstrom': 'maelstrom',
    'Allan Kingdom': 'allankingdom',
    'Alexander 23': 'alexander23',
    'Reo Cragun': 'reocragun',
    'sam gellaitry': 'samgellaitry',
    'Sophia Alexa': 'sophiaalexa',
    'NOTD': 'notd',
    'AbJo': 'abjo',
    'camoufly': 'camoufly',
    'Heno.': 'heno',
    'Medasin': 'medasin',
    'bloody white': 'bloodywhite',
    'BRUX': 'brux',
    'Sango': 'sango',
    'TOKiMONSTA': 'tokimonsta',
    'josh pan': 'joshpan',
    'Pauline Herr': 'paulineherr',
    'Boys Noize': 'boysnoize',
    'Poolside': 'poolside',
    'pollen': 'pollen',
    'Vic Mensa': 'vicmensa',
    'the park': 'thepark',
    'Pat Lok': 'patlok',
    'Bobby Shmurda': 'shmurda',
    'Harry Hudson': 'harryhudson',
    'Ibn Inglor': 'ibninglor',
    'TOMI': 'tomi',
    'jutes': 'jutes',
    'Lyrah': 'lyrah',
    'KILO KISH': 'kilokish',
    'MoRuf': 'moruf',
    'TK': 'tk',
    'Jesse Boykins III': 'jesseboykins3rd',
    'Siimbiie Lakew': 'siimbiie',
    'TiKA': 'tika',
    'Clear eyes': 'cleareyes',
    'Ben Kessler': 'benkessler',
    'BLONDISH': 'blondish',
    'SassyBlack': 'sassyblack',
    'McClenney': 'mcclenney',
    'Karma.wav': 'karmawav',
    'MELVV': 'melvv',
    'Kaien Cruz': 'kaiencruz',
    'Dot': 'dot',
    'Alaina Castillo': 'alainacastillo',
    'Peter Saputo': 'pjsaputo',
    'TWERL': 'twerl',
    'slenderbodies': 'slenderbodies',
    'Jacques Greene': 'jacquesgreene',
    'DRAMA': 'thedramaduo',
    'oksami': 'oksami',
    'Giraffage': 'giraffage',
    'Party Pupils': 'partypupils',
    'Alec King': 'alecking',
    'LAKIM': 'lakim',
    'Alexander Lewis': 'alexanderlewis',
    'superflirt': 'superflirt',
    'Tess Henley': 'tesshenley',
    'Black Dave': 'blackdave',
    'Mark Johns': 'itsmarkjohns',
    'DAZ MERCHANT': 'dazmerchant',
    'Whethan': 'whethan',
    'SLOE JACK': 'sloejack',
    'DNMO': 'iamdnmo',
    'Two Feet': 'twofeet',
    'Tensnake': 'tensnake',
    'Ruby Red': 'rubyred',
    'findokmusic': 'findokmusic',
    'DLG.': 'dlg',
    'msft': 'msft',
    'Suki Waterhouse': 'sukiwaterhouse',
    'Hayley Gene Penner': 'hayleygenepenner',
    'alara': 'alara',
    'DEFFIE': 'deffie',
    '3V3RY1': '3v3ry1',
    'Beauty School Dropout': 'beautyschooldropout',
    'harris cole': 'harriscole',
    'GLOWSTONE': 'glowstone',
    'krs': 'krs',
    'Felly': 'felly',
    'Munn': 'munn',
    'iamnobodi': 'iamnobodi',
    'J.Robb': 'jrobb',
    'Jamee Cornelia': 'jameecornelia',
    'LNRZ': 'lnrz',
    'Street Fever': 'streetfever',
    'Sherwyn': 'sherwyn',
    'REINEN': 'reinenr3alm',
    'nova': 'nova',
    'Devault': 'devault',
    'Being There': 'beingthere',
    'Carla the Poet': 'carlathepoet',
    'Duskus': 'duskus',
    'Jez Dior': 'jezdior',
    'RIZ LA VIE ': 'rizlavie',
    'YahZarah': 'yahzarah',
    'Kate Nash': 'katenash',
    'grentperez': 'grentperez',
    'vaultboy': 'vaultboy',
    'Queen George': 'queengeorge',
    'sad alex': 'sadalex',
    'Thomas Jack': 'thomasjack',
    'Brandon Banks': 'brandonbanks',
    'Camden': 'camden_music',
    'Bearson': 'bearson',
    'alann8h': 'alann8h',
    'Cameron Avery': 'cameronavery',
    'Brevin Kim': 'brevinkim',
    'Jerry Folk': 'jerryfolk',
    'Luca Maxim': 'lucamaxim',
    'ROZET': 'rozetzetzet',
    'dwilly': 'dwilly',
    'Devin Tracy': 'devintracy',
    'Gigamesh': 'gigamesh',
    'tulengua': 'tulengua'
}